Revert "pppdump: support building with the system zlib (#189)"
This reverts commit c98cc28f128dffc456488c74b600640057da6994
because of compile errors in pppdump:

cc  -o pppdump pppdump.o deflate.o bsd-comp.o  -lz
/usr/bin/ld: deflate.o: in function `z_incomp':
deflate.c:(.text+0x99): undefined reference to `inflateIncomp'
/usr/bin/ld: deflate.o: in function `z_decomp_alloc':
deflate.c:(.text+0x355): undefined reference to `inflateInit2'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:38: pppdump] Error 1

The copy of zlib here is not the same as the standard upstream zlib;
this version has some extra functions added.

Signed-off-by: Paul Mackerras <paulus@ozlabs.org>