Fix libsystemd detection
1. Use uppercase for `prefix` parameter
   `SYSTEMD_CFLAGS` is used elsewhere so `prefix` cannot be lowercase.
   https://autotools.info/pkgconfig/pkg_check_modules.html

2. The module name should be `libsystemd`
   Previously it will result in the following compile error when building pppd/auth.c:
   > /usr/bin/ld: pppd-auth.o: undefined reference to symbol 'sd_notify@@LIBSYSTEMD_209'
   > /usr/bin/ld: /usr/lib/libsystemd.so.0: error adding symbols: DSO missing from command line

   This is due to missing `-lsystemd-daemon` flag which is provided by `libsystemd-daemon-devel`
   package on Debian or `systemd-libs` on ArchLinux. And the proper .pc file in the package is
   `libsystemd` not `systemd`.
   https://stackoverflow.com/a/38303241

Signed-off-by: Chocobo1 <Chocobo1@users.noreply.github.com>