pppd: workaround sparc <asm/termbits.h> issue
The SPARC version of the <asm/termbits.h> kernel header has an issue:
it defines "struct termio", which conflicts with the definition in
<bits/ioctl-types.h>, causing a build failure in pppd.

This issue was fixed in the upstream Linux kernel in commit
c32d18e7942d7589b62e301eb426b32623366565 ("sparc: move struct termio
to asm/termios.h"), which is going to appear in Linux 6.10.

In order to support building with older toolchains, this patch
includes in the pppd source code a copy of the fixed SPARC
<asm/termbits.h> in the pppd code base, and uses it if we're on SPARC
with kernel headers older than 6.10.

Fixes:

In file included from termios_linux.h:39:
/home/thomas/projets/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/asm/termbits.h:17:8: error: redefinition of ‘struct termio’
   17 | struct termio {
      |        ^~~~~~
  CC       pppd-ipv6cp.o
In file included from /home/thomas/projets/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/sys/ioctl.h:29,
                 from sys-linux.c:76:
/home/thomas/projets/buildroot/output/host/sparc64-buildroot-linux-gnu/sysroot/usr/include/bits/ioctl-types.h:36:8: note: originally defined here
   36 | struct termio
      |        ^~~~~~

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>