Fix build when libc doesn't have shadow password support
Building ppp using uclibc, which doesn't have shadow password support,
gets this error:

session.c:76:20: error: shadow.h: No such file or directory

This fixes it.

Signed-off-by: Paul Mackerras <paulus@samba.org>