pppd: Fix build without OpenSSL (#533)
The symbol OPENSSL_VERSION_NUMBER is not defined when pppd is
compiled without OpenSSL support, so it evaluates to zero.
This results in the following linker error:

crypto.c:241: undefined reference to `ERR_free_strings'

Signed-off-by: Tomas Paukrt <tomaspaukrt@email.cz>